version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.5-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
      - image: circleci/postgres:9.4.12-alpine
        encironment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results
